// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy-7OAZVgc8Hmpgzgy5N9R5yt1PcDLGjE',
    appId: '1:1026566966531:web:d6c92edfa20151b0c1ed36',
    messagingSenderId: '1026566966531',
    projectId: 'tuduu-73ae0',
    authDomain: 'tuduu-73ae0.firebaseapp.com',
    storageBucket: 'tuduu-73ae0.appspot.com',
    measurementId: 'G-8JXPW2DWRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG1lk1XcbvDNk8z2C_jD_zOb2dcDHWavM',
    appId: '1:1026566966531:android:3101fbb0ebd353cfc1ed36',
    messagingSenderId: '1026566966531',
    projectId: 'tuduu-73ae0',
    storageBucket: 'tuduu-73ae0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEB7JpvQQfAHA3aXTZGDCs8-SOl4mz7K0',
    appId: '1:1026566966531:ios:e75d5c7215f05e57c1ed36',
    messagingSenderId: '1026566966531',
    projectId: 'tuduu-73ae0',
    storageBucket: 'tuduu-73ae0.appspot.com',
    iosBundleId: 'com.astropawlabs.tuduu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEB7JpvQQfAHA3aXTZGDCs8-SOl4mz7K0',
    appId: '1:1026566966531:ios:e75d5c7215f05e57c1ed36',
    messagingSenderId: '1026566966531',
    projectId: 'tuduu-73ae0',
    storageBucket: 'tuduu-73ae0.appspot.com',
    iosBundleId: 'com.astropawlabs.tuduu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy-7OAZVgc8Hmpgzgy5N9R5yt1PcDLGjE',
    appId: '1:1026566966531:web:182e2a28ceb45d4bc1ed36',
    messagingSenderId: '1026566966531',
    projectId: 'tuduu-73ae0',
    authDomain: 'tuduu-73ae0.firebaseapp.com',
    storageBucket: 'tuduu-73ae0.appspot.com',
    measurementId: 'G-N8D998S7BB',
  );
}
